### ISSUE TITLE
Target not working in macros

### ISSUE THREAD

**Issue by X3llus** [Athavar/Athavar.FFXIV.Plugin#57]
In the macros section of the toolbox I'm trying to create add in a /target line but the second I run it and it hits that line my game completely freezes and even after waiting a minute it doesn't seem to auto-resolve so I have to end task it and reboot the game.

**Comment by Athavar** [comment]
Thanks for reporting this. The cause of the freezes is that the `/target` contains a lookup to the ObjectTable to find a target with the set name. 
With commit e7a04663df7a5be123838f9c8c3bee8bb76b9ab8 I have changed the code to run this lookup on a framework thread, because access without it is deprecated.
But this is causing a problem with the task/thread that is used for the macro loop.
With `2.2.1.9` I have fixed that the execution is continued on the original context.

**Comment by X3llus** [comment]
Just tested the new update, seems to work good now
